apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hs9ie5a7h-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hs9ie5a7h-go 
  name: hs9ie5a7h-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hs9ie5a7h-go 
