apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hs9ie5a7h-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:9a5efe49871148dcce46bc4e874cb3d73fbb7fbf@sha256:3445f5dec8ab7add11535cec552d920d38bf49b7db977b13ee68652c906e5176
          name: container-image
